.TH "session.c" 3 "Mon Mar 13 2023" "Version V 1.0" "Librarire INET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
session.c \- Implémentation de la couche Session\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include <libgen\&.h>\fP
.br
\fC#include <arpa/inet\&.h>\fP
.br
\fC#include 'session\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_CLTS_WAIT\fP   5"
.br
.RI "Nombre maximal de clients en attente de connexion (listen) "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBadr2struct\fP (struct sockaddr_in *addr, char *adrIP, short port)"
.br
.RI "Transformer une adresse au format humain en structure SocketBSD\&. "
.ti -1c
.RI "\fBsocket_t\fP \fBcreerSocket\fP (int mode)"
.br
.RI "Création d'une socket de type DGRAM/STREAM\&. "
.ti -1c
.RI "\fBsocket_t\fP \fBcreerSocketAdr\fP (int mode, char *adrIP, short port)"
.br
.RI "Création d'une socket de type DGRAM/STREAM\&. "
.ti -1c
.RI "\fBsocket_t\fP \fBcreerSocketEcoute\fP (char *adrIP, short port)"
.br
.RI "Création d'une socket d'écoute avec l'adressage fourni en paramètre\&. "
.ti -1c
.RI "\fBsocket_t\fP \fBaccepterClt\fP (const \fBsocket_t\fP sockEcoute)"
.br
.RI "Acceptation d'une demande de connexion d'un client\&. "
.ti -1c
.RI "\fBsocket_t\fP \fBconnecterClt2Srv\fP (char *adrIP, short port)"
.br
.RI "Crétaion d'une socket d'appel et connexion au seveur dont l'adressage est fourni en paramètre\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char * \fBprogName\fP"
.br
.RI "Nom de l'exécutable\&. "
.in -1c
.SH "Detailed Description"
.PP 
Implémentation de la couche Session\&. 


.PP
\fBAuthor\fP
.RS 4
Samir El Khattabi 
.RE
.PP
\fBDate\fP
.RS 4
3 mars 2023 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define MAX_CLTS_WAIT   5"

.PP
Nombre maximal de clients en attente de connexion (listen) 
.SH "Function Documentation"
.PP 
.SS "\fBsocket_t\fP accepterClt (const \fBsocket_t\fP sockEcoute)"

.PP
Acceptation d'une demande de connexion d'un client\&. 
.PP
\fBParameters\fP
.RS 4
\fIsockEcoute\fP : socket d'écoute pour réception de la demande 
.RE
.PP
\fBReturns\fP
.RS 4
socket (dialogue) connectée par le serveur avec un client 
.RE
.PP

.SS "void adr2struct (struct sockaddr_in * addr, char * adrIP, short port)"

.PP
Transformer une adresse au format humain en structure SocketBSD\&. 
.PP
\fBParameters\fP
.RS 4
\fIaddr\fP : structure d'adressage BSD d'une socket INET 
.br
\fIadrIP\fP : adresse IP de la socket créée 
.br
\fIport\fP : port de la socket créée 
.RE
.PP
\fBNote\fP
.RS 4
Le domaine dépend du mode choisi (TCP/UDP) 
.RE
.PP
\fBReturns\fP
.RS 4
paramètre *adr modifié 
.RE
.PP

.SS "\fBsocket_t\fP connecterClt2Srv (char * adrIP, short port)"

.PP
Crétaion d'une socket d'appel et connexion au seveur dont l'adressage est fourni en paramètre\&. 
.PP
\fBParameters\fP
.RS 4
\fIadrIP\fP : adresse IP du serveur à connecter 
.br
\fIport\fP : port TCP du serveur à connecter 
.RE
.PP
\fBReturns\fP
.RS 4
socket connectée au serveur fourni en paramètre 
.RE
.PP

.SS "\fBsocket_t\fP creerSocket (int mode)"

.PP
Création d'une socket de type DGRAM/STREAM\&. 
.PP
\fBParameters\fP
.RS 4
\fImode\fP : mode connecté (STREAM) ou non (DGRAM) 
.RE
.PP
\fBReturns\fP
.RS 4
socket créée selon le mode choisi 
.RE
.PP

.SS "\fBsocket_t\fP creerSocketAdr (int mode, char * adrIP, short port)"

.PP
Création d'une socket de type DGRAM/STREAM\&. 
.PP
\fBParameters\fP
.RS 4
\fImode\fP : adresse IP de la socket créée 
.br
\fIadrIP\fP : adresse IP de la socket créée 
.br
\fIport\fP : port de la socket créée 
.RE
.PP
\fBReturns\fP
.RS 4
socket créée dans le domaine choisi avec l'adressage fourni 
.RE
.PP

.SS "creerSocketEcoute (char * adrIP, short port)"

.PP
Création d'une socket d'écoute avec l'adressage fourni en paramètre\&. 
.PP
\fBParameters\fP
.RS 4
\fIadrIP\fP : adresse IP du serveur à mettre en écoute 
.br
\fIport\fP : port TCP du serveur à mettre en écoute 
.RE
.PP
\fBReturns\fP
.RS 4
socket créée avec l'adressage fourni en paramètre 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "char* progName"

.PP
Nom de l'exécutable\&. Nom de l'exécutable : libnet nécessite cette variable qui pointe sur argargv[0]\&.
.PP
\fBNote\fP
.RS 4
Variable externe : à déclarer par l'utilisateur 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Librarire INET from the source code\&.
