.TH "session.h" 3 "Mon Mar 13 2023" "Version V 1.0" "Librarire INET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
session.h \- Spécification de la Session\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <unistd\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <netinet/in\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBsocket\fP"
.br
.RI "Définition de la structure de données socket\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCHECK\fP(sts,  msg)   if ((sts)==\-1) {perror(msg); exit(\-1);}"
.br
.RI "Macro-fonction qui vérifie que sts est différent de -1 (cas d'erreur) En cas d'erreur, il y a affichage du message adéquat et fin d'exécution 
.br
 "
.ti -1c
.RI "#define \fBPAUSE\fP(msg)   printf('%s [Appuyez sur entrée pour continuer]', msg); getchar();"
.br
.RI "Macro-fonction qui affiche msg et attend une entrée clavier 
.br
 "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBsocket\fP \fBsocket_t\fP"
.br
.RI "Définition du type de données socket_t\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBadr2struct\fP (struct sockaddr_in *addr, char *adrIP, short port)"
.br
.RI "Transformer une adresse au format humain en structure SocketBSD\&. "
.ti -1c
.RI "\fBsocket_t\fP \fBcreerSocket\fP (int mode)"
.br
.RI "Création d'une socket de type DGRAM/STREAM\&. "
.ti -1c
.RI "\fBsocket_t\fP \fBcreerSocketAdr\fP (int mode, char *adrIP, short port)"
.br
.RI "Création d'une socket de type DGRAM/STREAM\&. "
.ti -1c
.RI "\fBsocket_t\fP \fBcreerSocketEcoute\fP (char *adrIP, short port)"
.br
.RI "Création d'une socket d'écoute avec l'adressage fourni en paramètre\&. "
.ti -1c
.RI "\fBsocket_t\fP \fBaccepterClt\fP (const \fBsocket_t\fP sockEcoute)"
.br
.RI "Acceptation d'une demande de connexion d'un client\&. "
.ti -1c
.RI "\fBsocket_t\fP \fBconnecterClt2Srv\fP (char *adrIP, short port)"
.br
.RI "Crétaion d'une socket d'appel et connexion au seveur dont l'adressage est fourni en paramètre\&. "
.in -1c
.SH "Detailed Description"
.PP 
Spécification de la Session\&. 


.PP
\fBAuthor\fP
.RS 4
Samir El Khattabi 
.RE
.PP
\fBDate\fP
.RS 4
3 mars 2023 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define CHECK(sts, msg)   if ((sts)==\-1) {perror(msg); exit(\-1);}"

.PP
Macro-fonction qui vérifie que sts est différent de -1 (cas d'erreur) En cas d'erreur, il y a affichage du message adéquat et fin d'exécution 
.br
 
.SS "#define PAUSE(msg)   printf('%s [Appuyez sur entrée pour continuer]', msg); getchar();"

.PP
Macro-fonction qui affiche msg et attend une entrée clavier 
.br
 
.SH "Typedef Documentation"
.PP 
.SS "\fBsocket_t\fP"

.PP
Définition du type de données socket_t\&. 
.SH "Function Documentation"
.PP 
.SS "\fBsocket_t\fP accepterClt (const \fBsocket_t\fP sockEcoute)"

.PP
Acceptation d'une demande de connexion d'un client\&. 
.PP
\fBParameters\fP
.RS 4
\fIsockEcoute\fP : socket d'écoute pour réception de la demande 
.RE
.PP
\fBReturns\fP
.RS 4
socket (dialogue) connectée par le serveur avec un client 
.RE
.PP

.SS "void adr2struct (struct sockaddr_in * addr, char * adrIP, short port)"

.PP
Transformer une adresse au format humain en structure SocketBSD\&. 
.PP
\fBParameters\fP
.RS 4
\fIaddr\fP : structure d'adressage BSD d'une socket INET 
.br
\fIadrIP\fP : adresse IP de la socket créée 
.br
\fIport\fP : port de la socket créée 
.RE
.PP
\fBNote\fP
.RS 4
Le domaine dépend du mode choisi (TCP/UDP) 
.RE
.PP
\fBReturns\fP
.RS 4
paramètre *adr modifié 
.RE
.PP

.SS "\fBsocket_t\fP connecterClt2Srv (char * adrIP, short port)"

.PP
Crétaion d'une socket d'appel et connexion au seveur dont l'adressage est fourni en paramètre\&. 
.PP
\fBParameters\fP
.RS 4
\fIadrIP\fP : adresse IP du serveur à connecter 
.br
\fIport\fP : port TCP du serveur à connecter 
.RE
.PP
\fBReturns\fP
.RS 4
socket connectée au serveur fourni en paramètre 
.RE
.PP

.SS "\fBsocket_t\fP creerSocket (int mode)"

.PP
Création d'une socket de type DGRAM/STREAM\&. 
.PP
\fBParameters\fP
.RS 4
\fImode\fP : mode connecté (STREAM) ou non (DGRAM) 
.RE
.PP
\fBReturns\fP
.RS 4
socket créée selon le mode choisi 
.RE
.PP

.SS "\fBsocket_t\fP creerSocketAdr (int mode, char * adrIP, short port)"

.PP
Création d'une socket de type DGRAM/STREAM\&. 
.PP
\fBParameters\fP
.RS 4
\fImode\fP : adresse IP de la socket créée 
.br
\fIadrIP\fP : adresse IP de la socket créée 
.br
\fIport\fP : port de la socket créée 
.RE
.PP
\fBReturns\fP
.RS 4
socket créée dans le domaine choisi avec l'adressage fourni 
.RE
.PP

.SS "\fBsocket_t\fP creerSocketEcoute (char * adrIP, short port)"

.PP
Création d'une socket d'écoute avec l'adressage fourni en paramètre\&. 
.PP
\fBParameters\fP
.RS 4
\fIadrIP\fP : adresse IP du serveur à mettre en écoute 
.br
\fIport\fP : port TCP du serveur à mettre en écoute 
.RE
.PP
\fBReturns\fP
.RS 4
socket créée avec l'adressage fourni en paramètre 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Librarire INET from the source code\&.
